apiVersion: batch/v1
kind: Job
metadata:
  name: anomaly-detection-job
spec:
  template:
    spec:
      containers:
      - name: anomaly-detection
        image: workload-anomaly-detection:latest  # Use the locally built image
        imagePullPolicy: Never  # Prevent Kubernetes from pulling the image from a remote registry
      restartPolicy: Never

