apiVersion: batch/v1
kind: Job
metadata:
  name: human-object-interaction-job
spec:
  template:
    spec:
      containers:
      - name: human-object-interaction
        image: workload-human-object-interaction:latest  # Use the locally built image
        imagePullPolicy: Never  # Prevent Kubernetes from trying to pull the image from a registry
      restartPolicy: Never

