apiVersion: batch/v1
kind: Job
metadata:
  name: operational-efficiency-job-v2
spec:
  template:
    spec:
      containers:
      - name: operational-efficiency
        image: ghcr.io/glaciation-heu/dell-uc/workload_operational_efficiency:latest
        imagePullPolicy: IfNotPresent
      restartPolicy: Never
