apiVersion: batch/v1
kind: Job
metadata:
  name: human-object-interaction-job-v2
spec:
  template:
    spec:
      containers:
      - name: human-object-interaction
        image:  ghcr.io/glaciation-heu/dell-uc/workload_human_object_interaction:latest 
        imagePullPolicy: IfNotPresent
      restartPolicy: Never
